import "./globals.css";

import { Toaster } from "sonner";

import { AppShell } from "../components/app-shell";

export const metadata = {
  title: "耗材管理系统",
  description: "拓竹耗材管理系统（局域网 MQTT）"
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-CN">
      <body className="min-h-screen bg-background font-sans antialiased">
        {/* Runtime config for prebuilt images (generated by container entrypoint). */}
        <script src="/runtime-config.js" />
        <AppShell>{children}</AppShell>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}


